sysnews2/sysnews/api/urls.py
from django.urls import path, include
from .views import NewsView
from rest_framework import routers

router = routers.DefaultRouter()
# router.register('news',views.NewsView)

urlpatterns = [
    path ('news/', NewsView.as_view())
]

sysnews2/sysnews/news/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import NewsDetailView,NewsListView, CreateNews, DeleteNews, NewsUpdate, sourceList, sourceAdd, tagList, tagsAdd
# from .views import HomePageView

news_patterns = ([
     path('', login_required(NewsListView.as_view()), name='news'),
     path('<int:pk>/<slug:slug>/', login_required(NewsDetailView.as_view()), name='detail'),
     path('update/<int:pk>', login_required(NewsUpdate.as_view()), name='update'),
     path('delete/<int:pk>', login_required(DeleteNews.as_view()), name='delete'),
     path('create/',  login_required(CreateNews.as_view()), name='create'),
     # path('add_source',  login_required(SourceCreate.as_view()), name='add_source'),
     # path('add_tags',  login_required(TagsCreate.as_view()), name='add_tags'),
     path('source_list', sourceList, name='source_list' ),
     path('source_add', sourceAdd, name='source_add' ),
     path('tags_list', tagList, name='tags_list'),
     path('tags_add', tagsAdd, name='tags_add'),
], 'news')

sysnews2/sysnews/sysnews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from news.urls import news_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('news/', include(news_patterns)),
    path('accounts/',include('django.contrib.auth.urls')),
    #api
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysnews2/sysnews/news/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tags(models.Model):
    name = models.CharField(max_length=45, verbose_name="Nombre", unique=True)
    description = models.TextField(verbose_name="Descripción", null=True, blank=True)
    state = models.BooleanField(verbose_name="Estado", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
        ordering = ['-created']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/"

class Country(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nombre")
    country_cod = models.CharField(max_length=200, verbose_name="Codpais", null=True, blank=True)
    description = models.TextField(max_length=100, verbose_name="Descripción", null=True, blank=True)
    image = models.ImageField(upload_to='countries/')
    state = models.BooleanField(verbose_name="Estado", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Pais"
        verbose_name_plural = "Paises"
        ordering = ['-created']

    def __str__(self):
        return self.name

class Source(models.Model):
    name = models.CharField(max_length=45, unique=True, verbose_name="Nombre")
    description = models.TextField(max_length=100, verbose_name="Descripción", null=True, blank=True)
    state = models.BooleanField(verbose_name="Estado", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "fuente"
        verbose_name_plural = "fuentes"
        ordering = ['-created']

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return "/"


class News(models.Model):
    url = models.CharField(max_length=400, verbose_name="URL Principal")
    title = models.CharField(max_length=400, verbose_name="Titulo")
    headline = models.TextField(verbose_name="Encabezado", null=True, blank=True)
    explanation = models.TextField(verbose_name="Cuerpo")
    publication_date = models.DateField(verbose_name="Fecha de publicación", null=True, blank=True)
    tags = models.ManyToManyField(Tags, verbose_name="Tags")
    image = models.ImageField(upload_to='imagenes/')
    source = models.ForeignKey(Source, verbose_name="Fuente", on_delete=models.CASCADE)
    editor = models.ForeignKey(User, verbose_name="Usuario", on_delete=models.CASCADE)
    country = models.ForeignKey(Country, verbose_name="Pais", on_delete=models.CASCADE)
    state = models.BooleanField(verbose_name="Estado", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"
        ordering = ['-created']

    def __str__(self):
        return self.title

sysnews2/sysnews/news/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import News, Source, Tags

class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        fields = (
                'url', 
                'title',
                'headline',
                'explanation',
                'publication_date',
                'tags',
                'image',
                'source',
                'country',
                # 'usuario',
                )
        
        widgets = {
            'url' : forms.URLInput(attrs={'class':'form-control','required':'required','placeholder':'https://'}),
            'title' : forms.TextInput(attrs={'class':'form-control','required':'required'}),
            'headline' : forms.Textarea(attrs={'class':'form-control','rows':3,'required':'required'}),
            'explanation' : forms.Textarea(attrs={'class':'form-control','rows':20,'required':'required'}),
            'publication_date' : forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control','type':'date','required':'required'}),
            'tags' : forms.SelectMultiple(attrs={'class':'form-control','required':'required'}),
            'image' : forms.ClearableFileInput(attrs={'class':'form-control-file','required':'required'}),
            'source' : forms.Select(attrs={'class':'form-control','required':'required'}),
            'country' : forms.Select(attrs={'class':'form-control','required':'required'}),
        }

class TagsForm(forms.ModelForm):

    class Meta:
        model = Tags
        fields = ('name', 
                'description',
                )
        
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control','required':'required'}),
            'description' : forms.Textarea(attrs={'class':'form-control','rows':3}),
        }

    # def clean_name(self):
    #     name =self.cleaned_data.get('name')
    #     if 'name' in self.changed_data:
    #         print ("hola")
    #         raise forms.ValidationError("el tag ya se ha agregado")
    #     return name
    

class SourceForm(forms.ModelForm):

    class Meta:
        model = Source
        fields = ('name', 
                'description',
                )
        
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control','required':'required'}),
            'description' : forms.Textarea(attrs={'class':'form-control','rows':3}),
        }
    
    # def clean_name(self):
    #     name =self.cleaned_data.get('name')
    #     if name in self.changed_data:
    #         raise forms.ValidationError("La fuente ya se ha agregado")
    #     return name

sysnews2/sysnews/news/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import View
from django.http import JsonResponse
from .models import News, Source, Tags
from .forms import NewsForm, SourceForm, TagsForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required, permission_required
from core.decorators import allowed_users
from django.utils.decorators import method_decorator
from django.http import HttpResponse
import json


# Create your views here.

@method_decorator(allowed_users(allowed_roles=['Editor','Admin','Visitor']),name="dispatch")
class NewsDetailView(DetailView):
    model = News

@method_decorator(allowed_users(allowed_roles=['Editor','Admin','Visitor']),name="dispatch")
class NewsListView(ListView):
    model = News

@method_decorator(allowed_users(allowed_roles=['Editor','Admin']),name="dispatch")
class CreateNews(CreateView):
    form_class = NewsForm
    template_name = 'news/news_create.html'
 
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.editor = self.request.user
        instance.save()
        form.save_m2m()
        # messages.success(request, "Successfully Created")
        return redirect('home')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_source'] = SourceForm
        context['form_tags'] = TagsForm
        context['sources'] = Source.objects.all()
        return context

@method_decorator(allowed_users(allowed_roles=['Editor','Admin']),name="dispatch")
class NewsUpdate(UpdateView):
    model = News
    form_class = NewsForm
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if self.object.editor != self.request.user:
            return HttpResponse('You are not authorized')
        return response

    def get_success_url(self):
        news = get_object_or_404(News, pk=self.kwargs['pk'])
        return reverse("news:detail", args=(news.id,slugify(news.title)))

@method_decorator(allowed_users(allowed_roles=['Editor','Admin']),name="dispatch")
class DeleteNews(DeleteView):
    model = News
    success_url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        #print(self.object.editor)  # aquí ya dejamos que el padre defina `self.object`
        #print (self.request.user)
        if self.object.editor != self.request.user:
            return HttpResponse('You are not authorized')
        return response

 
# ### Tags
# @method_decorator(allowed_users(allowed_roles=['Editor','Admin']),name="dispatch")
# class TagsCreate (CreateView):
#     form_class = TagsForm
#     success_url = reverse_lazy('news:create')    
#     template_name = 'news/tags_create.html'

@login_required
def sourceList(request):
    sources = Source.objects.all()
    sources = [ sourceSerializer(source) for source in sources ]
    return HttpResponse(json.dumps(sources),content_type='application/json')

def sourceSerializer(source):
    return {'id':source.id,'name':source.name}

@login_required
@allowed_users(allowed_roles=['Editor','Admin'])
def sourceAdd(request):
    form = SourceForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            source = Source(name=request.POST['name'])
            source.save()
            return JsonResponse({"message":"Successfully"})
        else:
            return HttpResponse(form.errors.as_json(), status = 400, content_type='application/json')
        
#tags
@login_required()
def tagList(request):
    tags = Tags.objects.all()
    tags = [ tagsSerializer(tag) for tag in tags ]
    return HttpResponse(json.dumps(tags),content_type='application/json')

def tagsSerializer(tag):
    return {'id':tag.id,'name':tag.name}

@login_required
@allowed_users(allowed_roles=['Editor','Admin'])
def tagsAdd(request):
    form = TagsForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            tags = Tags(name=request.POST['name'])
            tags.save()
            return JsonResponse({"message":"Successfully"})
        else:
            return HttpResponse(form.errors.as_json(), status = 400, content_type='application/json')
        

sysnews2/sysnews/news/templates/news/news_create.html
{% extends 'core/base.html' %}

{% block title %}
Agregar Noticia
{% endblock title %}

{% block content %}
  <h3 class="mt-2">
    Agregar Noticia
  </h3>
  <form id="addNews" class="mt-2" method="post" action="{% url 'news:create' %}" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
      <label for="tags">Tags</label>
      <div class="row">
        <div class="col-11">
          <select name="tags" id="id_tags" multiple="" class="form-control">
          </select>
        </div>
        <div class="col-1">
          <button type="button" id="btnTags" class="btn btn-outline-success" data-toggle="modal" data-target="#tagsModal">
            +
          </button>
        </div>
      </div>
    </div>
      
    
      <div class="form-group">
        <label for="fuente">Fuente</label>
        <div class="row" id="source-div">
          <div class="col-11">
            <select name="source" id="id_source" class="form-control" required="required">
              <option value="" id="loading">---------</option>
            </select>
          </div>
          <div class="col-1">
              <button type="button"  class="btn btn-outline-success" data-toggle="modal" data-target="#sourceModal">
                +
              </button>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="url">URL</label>
        {{ form.url }}
      </div>
      <div class="form-group">
        <label for="titulo">Título de la noticia</label>
        {{ form.title }}
      </div>
      <div class="form-group">
        <label for="imagen">Imagen</label>
        {{ form.image }}
      </div>
      <div class="form-group">
        <label for="encabezado">Encabezado de la noticia</label>
      {{ form.headline }}
      </div>
      <div class="form-group">
        <label for="cuerpo">Cuerpo de la noticia</label>
        {{ form.explanation }}
      </div>
      <div class="form-group">
        <label for="publication_date">Fecha de publicación</label>
        <input type="date" name="publication_date" id="publication_date" class="form-control">
      </div>
      <div class="form-group">
        <label for="imagen">País</label>
        {{ form.country }}
      </div>
      <button class="btn btn-primary form-control" type="submit">Guardar</button>
  </form>
  <hr>

  <!-- modal source -->
  <div class="modal fade" id="sourceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Agregar Fuente</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="source-form" class="mt-2" method="post">{% csrf_token %}
            <div class="form-group">
              <label for="nombre">Nombre:</label>
              <input type="text" id="name_source" class="form-control">
            </div>
            <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- modal tags -->
  <div class="modal fade" id="tagsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Agregar Tags</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="tags-form" class="mt-2" method="post">{% csrf_token %}
            <div class="form-group">
              <label for="nombre">Nombre:</label>
              <input type="text" id="name_tag" class="form-control">
                <!-- {{ form_source.name }} -->
            </div>
            <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


{% block script %}
<script>
  //load page
  $(document).ready(function(){
    var bac = $("#id_tags").val();
    tagslist(bac);
    mostrar();
    $('#id_source').select2();
    $('#id_tags').select2();
  });

  //focus textbox modal
  $('#sourceModal').on('shown.bs.modal', function () {
      $("#name_source").val('');
    $("#name_source").focus();
  });

  //Save Source
  $('#source-form').submit(function(e){
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    $.ajax({
      type:'POST',
      headers:{
        "X-CSRFToken": csrftoken
      },
      url:'{% url "news:source_add" %}',
      data: {
        name:$('#name_source').val()
      },
      success:function(jResults){
        alert("Fuente guardada exitosamente");
        $('#name_source').val('');
        $('#sourceModal').modal('hide')
        mostrar();
      },
      error: function(data){
        if (data.responseJSON.name!=""){
          alert(data.responseJSON.name[0].message);
        }
      }
    });
    e.preventDefault();
  });
  
  //fill select source
  function mostrar(){
    
    let dropdown = $('#id_source');
    dropdown.empty();

    $.ajax({
      url: '{% url "news:source_list" %}',
      type: 'GET',
      success: function(response){
        // dropdown.append($('<option></option>').attr('value',null).text("select source"));
        $.each(response, function(key, entry){
          dropdown.append($('<option></option>').attr('value', entry.id).text(entry.name));
                });
        $('#loading').text('Select Source');
      }
    });
  }

  //save tags
  $('#tags-form').submit(function(e){
    var bac = $("#id_tags").val();
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    $.ajax({
      type:'POST',
      headers:{
        "X-CSRFToken": csrftoken
      },
      url:'{% url "news:tags_add" %}',
      data: {
        name:$('#name_tag').val()
      },
      success:function(jResults){
        alert("Tag guardado exitosamente");
        $('#name_tag').val('');
        $('#tagsModal').modal('hide')
        tagslist(bac);
        let dropdownT = $('#id_tags');
      },
      error: function(data){
        if (data.responseJSON.name!=""){
          alert(data.responseJSON.name[0].message);
        }
      }
    });
    e.preventDefault();
  });

  //fill select tags
  function tagslist(bac){
    let dropdownT = $('#id_tags');
    dropdownT.empty();
    console.log(bac);
    $.ajax({
      url: '{% url "news:tags_list" %}',
      type: 'GET',
      success: function(response){
        if (bac==""){
          $.each(response, function(key, entry){
          // console.log("valor: "+element);
          dropdownT.append($('<option></option>').attr('value', entry.id).text(entry.name));
          });
        }
        else{
          // bac.forEach(element => {
          for (var i = 0; i < bac.length ; i++) {
            $.each(response, function(key, entry){
              if (i<=bac.length){
                if(bac[i] == entry.id){
                  dropdownT.append($('<option selected></option>').attr('value', entry.id).text(entry.name));
                  i=i+1;
                }
                else{
                  dropdownT.append($('<option></option>').attr('value', entry.id).text(entry.name));
                }
              }
              else{
                dropdownT.append($('<option></option>').attr('value', entry.id).text(entry.name));
              }
            });
          }
        }
        
        $('#loading').text('Select Source');
      }
    });
  }

  $('#btnTasags').on('click',function(){
    var bac = $("#id_tags").val();
    console.log(bac);
  })
  
  function setInputDate(_id){
    var _dat = document.querySelector(_id);
    var hoy = new Date(),
        d = hoy.getDate(),
        m = hoy.getMonth()+1, 
        y = hoy.getFullYear(),
        data;

    if(d < 10){
        d = "0"+d;
    };
    if(m < 10){
        m = "0"+m;
    };

    data = y+"-"+m+"-"+d;
    // console.log(data);
    _dat.value = data;
  };
  // setInputDate("#calendar");
  setInputDate("#publication_date");
  </script>
<script>
  
</script>
{% endblock script %}
  

sysnews2/sysnews/news/templates/news/news_detail.html
{% extends 'core/base.html' %}
{% load user_tags %}
{% block title %}
{{ news.title }}
{% endblock title %}

{% block content %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-12">

        <p class="mt-4 lead">{{ news.country.name }}</p>
      <!-- Title -->
      <h1 class="mt-1" align="justify">{{ news.title }}</h1>

      <!-- Author -->
      <p class="lead">
        Publicado por
        <a>{{ news.editor.first_name }}</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Publicado el {{ news.publication_date }}</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" style="display:flex; margin:0 auto;" width="900" height="300" src="{{ news.image.url }}" alt="...">

      <hr>

      <!-- Post Content -->
      <p class="lead" align="justify">Tags: 
        {% for tag in news.tags.all %}
        {{ tag }}{% if not forloop.last %},{% endif %}          
        {% endfor %}
      </p>

      
      <blockquote class="blockquote">
        <p class="mb-0" align="justify">{{ news.headline }}</p>
      </blockquote>

      <p align="justify">{{ news.explanation|linebreaksbr }}</p>

      <hr>
      
      <blockquote class="blockquote">
        <footer class="blockquote-footer">
          <cite title="Source Title"><a href="{{ news.url }}">{{ news.url }}</a></cite>
          <p class="lead">
            Fuente: 
          <label>{{ news.source.name }}</label>
          </p>
        </footer>
    </blockquote>

    {% if request.user|has_group:'Editor' or request.user|has_group:'Admin' %}
    {% if request.user == news.editor %}
    <a href="{% url 'news:update' news.id %}"><button class="btn btn-warning">Editar</button></a>
    <hr>
    {% endif %}  
    {% endif %}  

    {% comment %}
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
  
        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
  
        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>
  
      </div>
    {% endcomment %}

  </div>
  </div>
{% endblock content %}

sysnews2/sysnews/news/templates/news/news_list.html
{% extends 'core/base.html' %}

{% block title %}
{{List news}}
{% endblock title %}

{% block content %}
<main role="main">
    <div class="container mb-4">
      {% for page in page_list|dictsort:"id" reversed %}
        <div class="row mt-3">
          <div class="col-md-9 mx-auto">
            <h2 class="mb-4">{{page.title}}</h2>
            <div>
              <p>{{page.content|striptags|safe|truncatechars:"200"}}</p>
              <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más</a>
                {% if request.user.is_staff %}
                  | <a href="{% url 'pages:update' page.id %}">Editar</a>
                  | <a href="{% url 'pages:delete' page.id %}">Borrar</a>
                {% endif %}
              </p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </main>
  {% endblock %}

  

sysnews2/sysnews/news/templates/news/source_create.html
{% extends 'core/base.html' %}

{% block title %}
{{ news.title }}
{% endblock title %}

{% block content %}

  <h3 class="mt-2">
    Agregar Fuente
  </h3>
  <form class="mt-2" method="post" action="{% url 'news:add_source' %}">{% csrf_token %}
    <div class="form-group">
        <label for="name_source">Nombre</label>
        {{ form.name }}
        {{ form.name.errors }}
    </div>
    <div style="margin-bottom: 42%;">
        <button class="btn btn-primary form-control" type="submit" style="margin-bottom: 1%;">Guardar</button>
        <a href="{% url 'news:create' %}" class="btn btn-success form-control">
            Atrás
        </a>
    </div>

  </form>
  <hr>

{% endblock content %}

  

sysnews2/sysnews/news/templates/news/tags_create.html
{% extends 'core/base.html' %}

{% block title %}
{{ news.title }}
{% endblock title %}

{% block content %}

  <h3 class="mt-2">
    Agregar Tag
  </h3>
  <form class="mt-2" method="post" action="{% url 'news:add_tags' %}">{% csrf_token %}
    <div class="form-group">
        <label for="name_source">Nombre</label>
        {{ form.name }}
        {{ form.name.errors }}
    </div>
    <div style="margin-bottom: 42%;">
        <button class="btn btn-primary form-control" type="submit" style="margin-bottom: 1%;">Guardar</button>
        <a href="{% url 'news:create' %}" class="btn btn-success form-control">
            Atrás
        </a>
    </div>

  </form>
  <hr>

{% endblock content %}

  